### ISSUE TITLE
kexec fails on Azure virtual machine running Debian 12 Bookworm

### ISSUE THREAD

**Issue by AkechiShiro** [numtide/nixos-anywhere#189] opened 2023-08-25 15:25 UTC
**Describe the bug**
```
[ 3099.239362] ima: impossible to appraise a kernel image without a file descriptor; try using kexec_file_load syscall.
[ 3895.765035] ima: impossible to appraise a kernel image without a file descriptor; try using kexec_file_load syscall.
kexec_load failed: Permission denied
```

**To Reproduce**

1. Use the simplest configuration and run --vm-test that works fine.
2. Try to ssh with the same config leads to this.

**Expected behavior**

Should kexec fails, I guess kexec_load_file should be tried ? This is due to IMA subsystem trying to be enforced on Azure machine I believe : https://kernsec.org/pipermail/linux-security-module-archive/2018-October/008951.html

> 
![image](https://github.com/numtide/nixos-anywhere/assets/14914796/28f6b5a8-62e2-4e27-9de8-5c3aebcbeb32)

It is due to the machine also being booted with SecureBoot.

**System information**

Debian Bookworm 12 : `Linux dev 6.1.0-10-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-2 (2023-07-27) x86_64 GNU/Linux`

**Additional context**

Specific issue to Azure VMs

A possible workaround may be ([source](https://lwn.net/Articles/752746/)): 

```
To use kexec_file_load() system call, instead of kexec_load(), at kexec
command, '-s' option must be specified. See [2] for a necessary patch for
kexec-tools.
```

I will try this workaround and open a PR if that fixes it.

**Comment by phaer** [comment] 2023-08-25 18:14
I think this is effectively a duplicate of https://github.com/numtide/nixos-anywhere/issues/143?

**Comment by AkechiShiro** [comment] 2023-08-25 18:17
@phaer I agree

**Closed** 2023-08-25 18:18 UTC
Labels: bug

**Comment by AkechiShiro** [comment] 2023-08-25 18:19
But even trying with kexec -s failed as well due to IMA being enforced.

IMA needs to be disabled on my VM, just so I can kexec.

**Comment by henrirosten** [comment] 2023-10-27 10:38
For future travelers attempting to make nixos-anywhere work with Azure VMs, this might become helpful: https://github.com/tiiuae/ghaf-infra/blob/main/docs/nixos-anywhere.md
